worker_role: worker-fromallall
worker_num_cpus: 8-fromallall
worker_num_cpu_cores_per_socket: 2-fromallall
worker_memory_gb: 32-fromallall
#worker_network_name: default-network-name-for-all-workers
worker_disk_gb: 250-fromallall
worker_ignition: master-fromallall

#worker_nodes:
# - name: sample_compute1
#   ip: 192.168.0.105
# - name: sample_compute2
#   ip: 192.168.0.106
# - name: sample_compute3
#   ip: 192.168.0.107

