---
- name: Extract network address from a CIDR
  ansible.builtin.set_fact:
     network_address: "{{ cluster_network_cidr | ansible.utils.ipaddr('network') }}"

- name: extract first 3 octets
  ansible.builtin.set_fact:
    first_three_octets: "{{ network_address.split('.')[:3] | join('.') }}"

- name: extract first 3 octets
  ansible.builtin.set_fact:
    ip_address: "{{ first_three_octets }}.{{ 250 | random(start=2) }}"

- name: Generate a random 4-character lowercase alphanumeric string
  ansible.builtin.set_fact:
    clustername: "ocp"
    hostid: "{{ lookup('community.general.random_string', length=4, special=false, upper=false, digits=true) }}"
#    random_ip: "{{ network_cidr | community.general.random_ip }}"

- name: set node variables for hostname and server role
  ansible.builtin.set_fact:
    hostname: "{{ clustername }}-{{ hostid }}"
    server_role: master

- name: display network_address
  ansible.builtin.debug:
    msg:
      - "cluster_network_cidr={{ cluster_network_cidr }}"
      - "network_address={{ network_address }}"
      - "first_three_octets={{ first_three_octets }}"
      - "ip_address={{ ip_address }}"

