---
- name: random IP
  ansible.builtin.set_fact:
     ip_address: "{{ network_subnet }}.{{ 250 | random(start=2) }}"

- name: Generate a random 4-character lowercase alphanumeric string
  ansible.builtin.set_fact:
    clustername: "ocp"
    hostid: "{{ lookup('community.general.random_string', length=4, special=false, upper=false, digits=true) }}"
#    random_ip: "{{ network_cidr | community.general.random_ip }}"

- name: set node variables for hostname and server role
  ansible.builtin.set_fact:
    hostname: "{{ clustername }}-{{ hostid }}"
    ip_address: "{{ ip_address }}"
    server_role: master

