---
- name: Get a DNS name and IP address
  import_tasks: getIPdns.yml

- name: display value within loop
  ansible.builtin.debug:
    msg:
      - "hostname={{ hostname }}"
      - "ip_address={{ ip_address }}"

# tasks file for defining a cluster node
- name: Jinja 2 template the node definition entry
  template:
    src:  nodedef_entry.j2
    dest:  "{{ temp_node_file.path }}"

- name: Append content from temporary file to config yaml
  ansible.builtin.shell: |
    cat "{{ temp_node_file.path }}" >> "{{ config_yaml_file }}"
