---
- name: Create temporary file for node definitions
  ansible.builtin.tempfile:
    state: file
    suffix: temp
  register: temp_node_file

- name: display varialbles
  debug:
    msg:
      - "temp_node_file: {{ temp_node_file }}"
      - "path: {{ temp_node_file.path }}"

- name: set file permissions
  ansible.builtin.file:
    path: "{{ temp_node_file.path }}"
    state: touch
    mode: 0666
