---
# tasks file for onboarding-variable-dump

#- name: print all variables
#  debug:
#    var=vars

- name: display varialbles
  debug:
    msg:
      - "mastercount: {{ mastercount }}"
      - "infracount: {{ infracount }}"
      - "workercount: {{ workercount }}"

- name: varlookup
  ansible.builtin.debug: msg="{{ lookup('ansible.builtin.varnames', '^vsphere.*') }}"

- name: varlook
  ansible.builtin.debug: msg="{{ q('varnames', 'vsphere.') }}"
# ansible.builtin.debug: msg="{{ q('varnames', 'hosts') }}"

